apiVersion: batch/v1
kind: Job

metadata:
  name: crossval

spec:
  completions: 5
  parallelism: 5
  completionMode: Indexed

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: crossval

        image: anjaaivanovic/crossval-job:latest
        imagePullPolicy: IfNotPresent

        envFrom:
        - configMapRef:
            name: crossval-config

        env:
        - name: FOLD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']